import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  console.log({ useRouter });

  return (
    <div className={styles.container}>
      <Head>
        <title>MoFilms 📽</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home :p</h1>
    </div>
  );
}

// #ff2c1f
// #1f1f1f
// lato + work sans
