import Head from "next/head";
import { Spacer } from "@nextui-org/react";

import MostPopular from "../components/MostPopular";
import Trending from "../components/Trending";

import movieService from "../services/movies";

export default function Home({ popular, trending }) {
  return (
    <>
      <div>
        <Head>
          <title>MoFilms 📽</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MostPopular movies={popular} />

        <Spacer />
        <Trending movies={trending} />
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const { results: popular } = await movieService.popular();
  const { results: trending } = await movieService.trending();

  return {
    props: {
      popular,
      trending,
    },
  };
}
