import Head from "next/head";

import Discovers from "../components/Discovers";

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>MoFilms 📽</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Discover</h1>
        <Discovers />
      </div>
    </>
  );
}
