import Head from "next/head";
import { GetServerSideProps } from "next";
import { Spacer } from "@nextui-org/react";
import { SWRConfig } from "swr";

//components
import MostPopular from "components/MostPopular";
import Trending from "components/Trending";

//utils
import movieService from "services/movies";
import { MovieTopResponse } from "services/movies/top/types";
import { MoviesTrendingResponse } from "services/movies/trending/types";

//swr keys
//TODO: replace this with enums
import { swrMoviePopularKey } from "components/MostPopular";
import { swrMovieTrendingKey } from "components/Trending";

interface Props {
  fallback: {
    [swrMoviePopularKey]: MovieTopResponse[];
    [swrMovieTrendingKey]: MoviesTrendingResponse[];
  };
}

export default function Home({ fallback }: Props) {
  return (
    <>
      <div>
        <Head>
          <title>MoFilms 📽</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <SWRConfig value={{ fallback }}>
          <MostPopular />

          <Spacer />
          <Trending />
        </SWRConfig>
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const topMovies = await movieService.topMovies();
  const trending = await movieService.trending();

  return {
    props: {
      fallback: {
        [swrMoviePopularKey]: topMovies,
        [swrMovieTrendingKey]: trending,
      },
    },
  };
};
